### PR TITLE
Custom dir support

### PR DESCRIPTION
**Pull request by pr0f35510n4l**
takes 2nd argument as outdir

### CODE REVIEW

**Comment by pr0f35510n4l** [comment]
wait no this breaks the code

**Comment by pr0f35510n4l** [comment]
Fixed. should work now

**Comment by pr0f35510n4l** [comment]
This will take second argument and change dir to user input

**Comment by extremecoders-re** [comment]
Thanks for taking the time to write a pull request. But in the current form the PR will not be merged.

As I notice, you're are accessing `sys.argv` in the `extractFiles`. In my opinion, parsing command line arguments at multiple places is not a good practice. I have mentioned in the [previous PR](https://github.com/extremecoders-re/pyinstxtractor/pull/4) the way to handle this would be to parse the command line in `main` and pass the directory as an optional argument.

Also I prefer a single commit rather than multiple commits for a fix/feature unless unforeseen.

**Pull request closed without merging**
